In [2]:
# import pandas
import pandas as pd
import numpy as np

In [ ]:
# Fill missing values

string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado']) # Series with missing values
string_data
print(string_data.isnull()) # Check for missing values
string_data[0] = None # Set first value to None
print(string_data.isnull()) # Check for missing values

# Methods for filling missing values

| Method        | Description                | Example                     |
|---------------|----------------------------|-----------------------------|
| `fillna`      | Fill missing values        | `df.fillna(0)`              |
| `ffill`       | Fill forward               | `df.fillna(method='ffill')` |
| `bfill`       | Fill backward              | `df.fillna(method='bfill')` |
| `dropna`      | Drop missing values        | `df.dropna()`               |
| `interpolate` | Interpolate missing values | `df.interpolate()`          |
| `replace`     | Replace missing values     | `df.replace(-999, np.nan)`  |
| `mask`        | Replace values with NaN    | `df.mask(df < 0)`           |
| `notnull`     | Negation of isnull         | `df.notnull()`              |

In [5]:
# N/A filtering 
from numpy import nan as NA

data = pd.Series([1, NA, 3.5, NA, 7])
print(data.dropna()) # Drop missing values
print(data[data.notnull()]) # Negation of isnull

data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna() # Drop missing values
data.dropna(how='all') # Drop rows with all missing values
data.dropna(axis=1, how='all') # Drop columns with all missing values
data.dropna(thresh=2) # Drop rows with at least 2 missing values
df = pd.DataFrame(np.random.randn(7, 3))

0    1.0
2    3.5
4    7.0
dtype: float64
0    1.0
2    3.5
4    7.0
dtype: float64
     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0
     0    1    2
0  1.0  6.5  3.0


# Dropna method arguments

| Argument | Description                  | Example                 |
|----------|------------------------------|-------------------------|
| `axis`   | Axis to drop values          | `df.dropna(axis=1)`     |
| `how`    | How to drop values           | `df.dropna(how='all')`  |
| `thresh` | Minimum non-NA values        | `df.dropna(thresh=2)`   |
| `subset` | Drop values in specific rows | `df.dropna(subset=[1])` |

In [ ]:
# NA Filling missing data

df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA

print(df.fillna(0)) # Fill missing values with 0
print(df.fillna({1: 0.5, 2: 0})) # Fill missing values with different values
print(df.fillna(method='ffill')) # Fill missing values with forward fill
print(df.fillna(method='ffill', limit=2)) # Fill missing values with forward fill with limit

In [ ]:
data = pd.Series([1., NA, 3.5, NA, 7])
print(data.fillna(data.mean())) # Fill missing values with mean

# Fillna method arguments

| Argument  | Description               | Example                     |
|-----------|---------------------------|-----------------------------|
| `value`   | Scalar value or dict-like | `df.fillna(0)`              |
| `method`  | Interpolation method      | `df.fillna(method='ffill')` |
| `axis`    | Axis to fill values       | `df.fillna(axis=1)`         |
| `limit`   | Maximum number of fills   | `df.fillna(limit=2)`        |
| `inplace` | Modify the calling object | `df.fillna(inplace=True)`   |

In [ ]:
# Data transformation

data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})
print(data)
data.duplicated() # Check for duplicates
data.drop_duplicates() # Drop duplicates
data['v1'] = range(7)
print(data.drop_duplicates(['k1'])) # Drop duplicates in specific columns
data.drop_duplicates(['k1', 'k2'], keep='last') # Drop duplicates and keep last

In [ ]:
# Data transformation with function mapping

data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

data['animal'] = data['food'].str.lower().map(meat_to_animal)

lowercased = data['food'].str.lower()
data['animal'] = lowercased.map(meat_to_animal)

data['food'].map(lambda x: meat_to_animal[x.lower()])

In [ ]:
# Data transformation with replacing values

data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace(-999, np.nan) # Replace single value
data.replace([-999, -1000], np.nan) # Replace multiple values
data.replace([-999, -1000], [np.nan, 0]) # Replace multiple values with different values
data.replace({-999: np.nan, -1000: 0}) # Replace multiple values with different values

In [ ]:
# Data transformation with renaming axis indexes

data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Ohio', 'Colorado', 'New York'], columns=['one', 'two', 'three', 'four'])
transform = lambda x: x[:4].upper() # Transform function for index

data.index.map(transform) # Transform index
data.index = data.index.map(transform) # Assign transformed index
data.rename(index=str.title, columns=str.upper) # Rename index and columns
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'}) # Rename index and columns
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'}, inplace=True) # Rename index and columns in place

In [6]:
# Data discretization and binning

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32] # Ages
bins = [18, 25, 35, 60, 100] # Bins
cats = pd.cut(ages, bins) # Discretize ages into bins
print(cats)
print(cats.codes)
print(cats.categories)
pd.Series(cats).value_counts() # Count values in bins
pd.cut(ages, [18, 26, 36, 61, 100], right=False) # Change side of interval

group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior'] # Group names
pd.cut(ages, bins, labels=group_names) # Assign group names

data = np.random.rand(20) # Random data
pd.cut(data, 4, precision=2) # Discretize data into 4 bins

data = np.random.randn(1000) # Random data
cats = pd.qcut(data, 4) # Quantile-based discretization
result = pd.Series(cats).value_counts() # Count values in bins
print(result)   

pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]) # Quantile-based discretization with custom quantiles


[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]
[0 0 0 1 0 0 2 1 3 2 2 1]
IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')
(-3.153, -0.603]     250
(-0.603, -0.0106]    250
(-0.0106, 0.681]     250
(0.681, 2.861]       250
Name: count, dtype: int64


In [4]:
# Detecting and filtering outliers

data = pd.DataFrame(np.random.randn(1000, 4)) # Random data
data.describe() # Describe data
print(data)

col = data[2] # Select column
col[np.abs(col) > 3] # Detect outliers

# outliers = data[(np.abs(data) > 3).any(1)] # Filter rows with outliers
# print(outliers)

data[np.abs(data) > 3] = np.sign(data) * 3 # Cap outliers
print(data)
np.sign(data).head() # Compute sign of each element

            0         1         2         3
0    0.610274  0.107496  0.031415 -2.269725
1   -2.227426 -0.115869 -1.052221  0.378565
2    0.894538 -0.057689  0.260617  0.844179
3   -0.439677 -2.904112  0.207828  0.381777
4   -0.294742  0.459073 -0.540913  0.473642
..        ...       ...       ...       ...
995 -1.398838  0.981642 -1.338814 -0.742624
996 -0.816035  0.697349 -0.371942 -0.808885
997  1.771979  0.723293  1.856136 -0.875286
998 -1.427003  0.370912 -0.434273 -1.093725
999 -0.403393  1.440555  1.702848 -0.562931

[1000 rows x 4 columns]
            0         1         2         3
0    0.610274  0.107496  0.031415 -2.269725
1   -2.227426 -0.115869 -1.052221  0.378565
2    0.894538 -0.057689  0.260617  0.844179
3   -0.439677 -2.904112  0.207828  0.381777
4   -0.294742  0.459073 -0.540913  0.473642
..        ...       ...       ...       ...
995 -1.398838  0.981642 -1.338814 -0.742624
996 -0.816035  0.697349 -0.371942 -0.808885
997  1.771979  0.723293  1.856136 -0.875286
998 -1.

0    1    2    3
0  1.0  1.0  1.0 -1.0
1 -1.0 -1.0 -1.0  1.0
2  1.0 -1.0  1.0  1.0
3 -1.0 -1.0  1.0  1.0
4 -1.0  1.0 -1.0  1.0

In [3]:
# Permutation and random sampling

df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4))) # Random data
sampler = np.random.permutation(5) # Permutation
df.take(sampler) # Permute rows
df.sample(n=3) # Random sampling without replacement
choices = pd.Series([5, 7, -1, 6, 4]) # Random data
draws = choices.sample(n=10, replace=True) # Random sampling with replacement
print(draws)

4    4
3    6
2   -1
1    7
2   -1
0    5
4    4
4    4
1    7
2   -1
dtype: int64


In [ ]:
# Computing indicator/dummy variables

df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)}) # Random data
print(df)
pd.get_dummies(df['key']) # Create dummy variables
dummies = pd.get_dummies(df['key'], prefix='key') # Create dummy variables with prefix
print(dummies)
df_with_dummy = df[['data1']].join(dummies) # Join dummy variables
print(df_with_dummy)

In [17]:
# MovieLens 1M dataset

mnames = ['movie_id', 'title', 'genres'] # Movie data
movies = pd.read_table('../../dataset/grouplens_1m_movies.zip', sep='::', header=None, names=mnames, engine='python', encoding='latin1')
print(movies.head())

all_genres = [] # All genres
for x in movies.genres:
    all_genres.extend(x.split('|'))
    
genres = pd.Series(all_genres).unique() # Unique genres
print(genres)

zero_matrix = np.zeros((len(movies), len(genres))) # Zero matrix
print(zero_matrix)

dummy = pd.DataFrame(zero_matrix, columns=genres) # Dummy variables

gen = movies.genres[0] # First genre
print(gen.split('|'))
print(dummy.columns.get_indexer(gen.split('|')))

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
['Animation' "Children's" 'Comedy' 'Adventure' 'Fantasy' 'Romance' 'Drama'
 'Action' 'Crime' 'Thriller' 'Horror' 'Sci-Fi' 'Documentary' 'War'
 'Musical' 'Mystery' 'Film-Noir' 'Western']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['Animation', "Children's", 'Comedy']
[0 1 2]
