In [1]:
import tensorflow as tf

In [2]:
# Constant Tensors
cons_tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Constant Tensor:")
print(cons_tensor)

# Operations on Tensors
squared = tf.square(cons_tensor)
print("\nSquared Tensor:")
print(squared)

# Operations with Different Data Types ( raises an error)
tf.constant([1.]) + tf.constant([2])

# tensors must be of the same type for operations
tf.cast(tf.constant([1]), tf.float32) + tf.constant([2.])

# Variable Tensors
var = tf.Variable([[1, 2, 3], [4, 5, 6]])
print("\nVariable Tensor before assignment:")
print(var)

var .assign([[7, 8, 9], [10, 11, 12]])
print("\nVariable Tensor after assignment:")
print(var)

# Other types of Tensors

# Sparse Tensor
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])

# TensorArray
tensor_array = tf.TensorArray(dtype=tf.float32, size=3)
tensor_array = tensor_array.write(0, [1.0, 2.0])

# Ragged Tensor
ragged_tensor = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])

# String Tensor
string_tensor = tf.constant(["Hello", "TensorFlow"])

# Sets
set_tensor = tf.constant([1, 2, 3, 2, 1])
unique_set_tensor = tf.unique(set_tensor)

# Tensor Queue
tensor_queue = tf.queue.FIFOQueue(capacity=5, dtypes=[tf.float32])
# Random Shuffle Queue
random_shuffle_queue = tf.queue.RandomShuffleQueue(capacity=5, min_after_dequeue=2, dtypes=[tf.float32])

# padding queues
padding_fifo_queue = tf.queue.PaddingFIFOQueue(capacity=5, dtypes=[tf.float32], shapes=[(None, 3)])

Constant Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Squared Tensor:
tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)


InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 

In [5]:
X = tf.range(10) # Create a Tensor with values from 0 to 9
dataset = tf.data.Dataset.from_tensor_slices(X) # Create a Dataset from Tensors

# Data Shuffle
dataset = tf.data.Dataset.range(10)
dataset = dataset.shuffle(buffer_size=5, seed=42).batch(4)
print([item for item in dataset])

[<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 2, 3, 6])>, <tf.Tensor: shape=(4,), dtype=int64, numpy=array([7, 9, 1, 8])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([4, 5])>]
