In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [3]:
# Multiply each sequence by 2

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 31.4 ms, sys: 7.67 ms, total: 39 ms
Wall time: 41.2 ms


In [5]:

%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 772 ms, sys: 198 ms, total: 970 ms
Wall time: 976 ms


In [6]:
# Convert a list to an array

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
# create array with zeroes, ones, empty

np.zeros(10)
np.zeros((3, 6))
np.ones(10)
np.ones((3, 6))

np.empty((2, 3, 2))

eye = np.eye(3)

iden = np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# create array with range
arr = np.arange(15)

# create array with shape
arr = np.arange(15).reshape((3, 5))

# create array w dtype
arr = np.array([1, 2, 3], dtype=np.float64)

# convert dtype to another
arr = np.array([1, 2, 3], dtype=np.float64)
arr.dtype = np.int64

arr1 = arr.astype(np.float64)


array([4.60718242e+18, 4.61168602e+18, 4.61393782e+18])

In [ ]:
# arithmetical operations w arrays

arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr * arr # elementwise multiplication
arr - arr # elementwise subtraction
1 / arr # elementwise division
arr ** 0.5 # elementwise square root

In [ ]:
# Indexing and slicing
arr = np.arange(10)
arr[5] # show 5 index
arr[5:8] # show 5 to 8 index
arr[5:8] = 12 # assign 12 to 5 to 8 index

# working w 2-dimension array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2] # show 2nd row
arr2d[0][2] # show 0th row 2nd column

# working w 3-dimension array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] # show 0th row
arr3d[0][1] # show 0th row 1st column
arr3d[0][1][2] # show 0th row 1st column 2nd element

# assign value to 2-dimension array
arr2d[0][2] = 5


In [ ]:
# Bool indexing

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7, 4)

data[names == 'Bob']
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

mask = (names == 'Bob') | (names == 'Will')
data[mask]

# opposite of mask
data[~mask]


In [ ]:
# Fancy indexing

arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

arr[[4, 3, 0, 6]]


In [ ]:
# Transposing arrays and swapping axes

arr = np.arange(15).reshape((3, 5))

arr.T

arr = np.random.randn(6, 3)

np.dot(arr.T, arr)
